/**
 * The Worker's probes, and the freshness contract they enforce.
 *
 * There is no DNS-only record and no origin bypass here. Every probe goes to the normal
 * proxied hostname, and the response has to prove it was generated by the origin for
 * *this* request rather than replayed by some cache. Three layers, none sufficient alone:
 *
 *   1. REQUEST -- a unique query string per probe (?nonce=<random>). A query string is
 *      part of the cache key, so a unique URL cannot collide with a stored copy. Plus
 *      cf: { cacheTtl: 0, cacheEverything: false } and Cache-Control: no-cache, so
 *      Cloudflare neither serves nor stores a copy for this URL.
 *   2. RESPONSE -- the origin must send a non-reusable Cache-Control (no-store, or
 *      max-age=0) plus Pragma: no-cache as asked. Without it the endpoint is cacheable
 *      and layer 1 is doing all the work.
 *   3. FRESHNESS PROOF -- for endpoints that can reflect the nonce, the response must
 *      echo the exact random value sent. A cached copy cannot know a value minted
 *      microseconds ago, so an echoed nonce is hard evidence the origin answered. Static
 *      file serving cannot echo, and those rows are declared echoNonce: false -- their
 *      honesty stops at layers 1 and 2, and the README says so rather than pretending
 *      otherwise.
 *
 * A probe that returns 200 but fails layer 2 or 3 is recorded as a FAILURE, not a pass.
 * That is the whole point: a page that stays green through a cache replay is the bug
 * this file exists to prevent.
 */
import {
  readHrtStats, readCommentsStats, readStoryCount, readCloudflareVisits,
  CF_PROBE_USER_AGENT,
} from '../../lib/probe.mjs'
import { COMPONENTS } from '../../lib/components.mjs'

export { CF_PROBE_USER_AGENT }

/** A body this large is not a health endpoint; read a prefix rather than the whole thing. */
const MAX_BODY_BYTES = 64 * 1024
const DEFAULT_TIMEOUT_MS = 4_000

/**
 * A response is non-reusable when the origin says so. `no-store` is the directive the
 * contract asks for. `max-age=0` (usually with must-revalidate) is accepted as
 * equivalent: it forbids serving a stored entry without contacting the origin, and it is
 * what Cloudflare Pages emits for kiramyao.com. A "public, max-age=N" response is not.
 */
const isNonCacheable = (cacheControl) => /(^|[\s,])no-store([\s,]|$)/i.test(cacheControl)
  || /(^|[\s,])max-age\s*=\s*0([\s,]|$)/i.test(cacheControl)
const isCachedStatus = (value) => /^(HIT|STALE|UPDATING)$/i.test(String(value ?? ''))

/** Make a whole response body small enough to inspect without trusting Content-Length. */
async function readCapped(res, limit) {
  const text = await res.text()
  return text.length > limit ? text.slice(0, limit) : text
}

/**
 * One freshness-checked probe.
 *
 * `expectEcho` is the per-row declaration from lib/components.mjs. The nonce is
 * always sent (it is what makes the URL unique); it is only *required* back where the
 * origin is app code that can reflect it.
 */
export async function probeFresh(url, {
  nonce, expectEcho = false, fetchImpl = fetch, timeoutMs = DEFAULT_TIMEOUT_MS,
} = {}) {
  const started = Date.now()
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  const target = new URL(url)
  target.searchParams.set('nonce', nonce)

  try {
    const res = await fetchImpl(target.toString(), {
      method: 'GET',
      redirect: 'follow',
      signal: controller.signal,
      headers: {
        // Identify honestly, and forbid a cached answer.
        'User-Agent': CF_PROBE_USER_AGENT,
        'Cache-Control': 'no-cache',
        Pragma: 'no-cache',
      },
      // Layer 1 at the Cloudflare layer: never reuse, never store.
      cf: { cacheTtl: 0, cacheEverything: false },
    })

    const body = await readCapped(res, MAX_BODY_BYTES)
    const cacheControl = res.headers.get('cache-control') ?? ''
    const pragma = res.headers.get('pragma') ?? ''
    const cacheStatus = res.headers.get('cf-cache-status')
    const age = Number(res.headers.get('age') ?? 0)
    const headerNonce = res.headers.get('x-probe-nonce')
    const echoed = body.includes(nonce) || headerNonce === nonce

    const statusOk = res.status >= 200 && res.status < 400
    const nonCacheable = isNonCacheable(cacheControl)

    let error = null
    if (!statusOk) error = `HTTP ${res.status}`
    else if (isCachedStatus(cacheStatus)) error = `cached copy answered (cf-cache-status: ${cacheStatus})`
    else if (Number.isFinite(age) && age > 0) error = `cached copy answered (Age: ${age}s)`
    else if (!nonCacheable) error = `origin did not declare a non-reusable response (Cache-Control: ${cacheControl || 'absent'})`
    else if (expectEcho && !echoed) error = 'nonce not echoed: the response was not generated for this request'

    return {
      ok: error === null,
      statusCode: res.status,
      latencyMs: Date.now() - started,
      error,
      // Evidence, kept on the result (and in the round log) for the report and for
      // debugging a red row: it is not written to the probes table, whose schema is fixed.
      nonce,
      echoed,
      expectEcho,
      cacheStatus: cacheStatus ?? null,
      ageSeconds: Number.isFinite(age) ? age : null,
      cacheControl,
      pragma,
      nonCacheable,
    }
  } catch (caught) {
    return {
      ok: false,
      statusCode: null,
      latencyMs: Date.now() - started,
      error: caught.name === 'AbortError' ? `timeout after ${timeoutMs}ms` : (caught.message || String(caught)),
      nonce,
      echoed: false,
      expectEcho,
      cacheStatus: null,
      ageSeconds: null,
      cacheControl: '',
      pragma: '',
      nonCacheable: false,
    }
  } finally {
    clearTimeout(timer)
  }
}

/** A fresh random nonce per probe. Collision is not a concern at this volume. */
export function probeNonce() {
  return crypto.randomUUID().replace(/-/g, '')
}

/** One round of external probes, sequential so the latencies stay comparable. */
export async function runWorkerProbeRound(store, config, { now = Date.now(), fetchImpl = fetch } = {}) {
  const results = []
  for (const component of COMPONENTS.filter((c) => c.local)) {
    const expectEcho = !!config.echoNonce?.[component.id]
    const nonce = probeNonce()
    const outcome = await probeFresh(config.targets[component.id], {
      nonce, expectEcho, fetchImpl,
    })
    await store.addProbe({ source: 'local', component: component.id, at: now, ...outcome })
    results.push({ component: component.id, ...outcome })
  }
  return results
}

/**
 * The guardian reads. These are data reads rather than liveness probes, so they get the
 * same cache bypass (not the nonce check): a stale count is still a lie about "now".
 */
function freshFetch(fetchImpl = fetch) {
  return (url, opts = {}) => fetchImpl(url, {
    ...opts,
    headers: { 'Cache-Control': 'no-cache', Pragma: 'no-cache', ...(opts.headers ?? {}) },
    cf: { ...(opts.cf ?? {}), cacheTtl: 0, cacheEverything: false },
  })
}

export async function runWorkerMetricsRound(store, config, { now = Date.now(), fetchImpl = fetch } = {}) {
  const guarded = freshFetch(fetchImpl)
  const [hrt, comments, stories] = await Promise.all([
    readHrtStats(config.stats.hrt, { fetchImpl: guarded }),
    readCommentsStats(config.stats.comments, { fetchImpl: guarded }),
    readStoryCount(config.stats.stories, { fetchImpl: guarded }),
  ])

  if (hrt.ok) {
    await store.addMetric('hrt.accounts', hrt.accounts, now)
    await store.addMetric('hrt.self_deletions', hrt.selfDeletions, now)
  }
  if (comments.ok) {
    await store.addMetric('comments.users', comments.users, now)
    await store.addMetric('comments.comments', comments.comments, now)
  }
  if (stories.ok) await store.addMetric('stories.preserved', stories.stories, now)

  if (config.cloudflare) {
    const visits = await readCloudflareVisits(config.cloudflare, { fetchImpl, now })
    if (visits.ok) {
      await store.addMetric('visits.site', visits.site, now)
      await store.addMetric('visits.tracker', visits.tracker, now)
    }
  }

  return { hrt, comments, stories }
}
